<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Launcher.props" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit"/>
    <PackageReference Include="NUnit.Analyzers"/>
    <PackageReference Include="NUnit3TestAdapter"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Marsey.Core\Marsey.Core.csproj"/>
    <ProjectReference Include="..\Marsey.LauncherIntegration\Marsey.LauncherIntegration.csproj"/>
    <ProjectReference Include="..\SS14.Launcher.Extensibility\SS14.Launcher.Extensibility.csproj"/>
    <ProjectReference Include="..\SS14.Launcher\SS14.Launcher.csproj"/>
  </ItemGroup>

</Project>
